server:
  port: 9000
spring:
  application:
    name: xczx-service-manage-cms
  data:
    mongodb:
      host: 127.0.0.1
      database: xc_cms
  rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: guest
      password: guest
      virtual-host: /